#!/usr/bin/env ruby
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

APP_PATH = File.expand_path( '../../config/application',  __FILE__ )
require File.expand_path( '../../config/boot',  __FILE__ )
require APP_PATH

Rails.application.require_environment!

if ARGV.size != 2
    puts <<-EOTXT
    Usage #{__FILE__} <e-mail> <password>
EOTXT

    exit 1
end

email    = ARGV.first.dup
password = ARGV[1].dup

if !(user = User.where( email: ARGV.first ).first)
    $stderr.puts "Could not find user with e-mail address '#{email}'."
    exit 1
end

if user.update( password: password )
    puts "User with e-mail address '#{user.email}' now has password '#{password}'."
    exit
end

$stderr.puts "User with e-mail address '#{user.email}' could not be updated because:"
$stderr.puts

user.errors.messages.each do |field, messages|
    $stderr.puts "'#{field}' field:"
    messages.each do |msg|
        $stderr.puts "  * #{msg}"
    end
end

exit 1
