#!/usr/bin/env ruby
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

APP_PATH = File.expand_path( '../../config/application',  __FILE__ )
require File.expand_path( '../../config/boot',  __FILE__ )
require APP_PATH

Rails.application.require_environment!

if ARGV.size != 3
    puts <<-EOTXT
    Usage #{__FILE__} <e-mail> <password> <full name>
    EOTXT

    exit 1
end

email    = ARGV.first.dup
password = ARGV[1].dup
name     = ARGV[2].dup

user = User.create( email: email, password: password, name: name )

if user.errors.empty?
    puts "User '#{name}' with e-mail address '#{user.email}' created with password '#{password}'."
    exit
end

$stderr.puts "User '#{name}' with e-mail address '#{user.email}' could not be created because:"
$stderr.puts

user.errors.messages.each do |field, messages|
    $stderr.puts "'#{field}' field:"
    messages.each do |msg|
        $stderr.puts "  * #{msg}"
    end
end

exit 1
